axis_0:
  ros__parameters:
    bus_number: 1
    board_address: 10
    step_delay_ms: 5
    max_power: 0.3
    holding_power: 0.1

axis_1:
  ros__parameters:
    bus_number: 1
    board_address: 11
    step_delay_ms: 5
    max_power: 0.3
    holding_power: 0.1

axis_2:
  ros__parameters:
    bus_number: 1
    board_address: 12
    step_delay_ms: 5
    max_power: 0.3
    holding_power: 0.1

axis_3:
  ros__parameters:
    bus_number: 1
    board_address: 13
    step_delay_ms: 5
    max_power: 0.3
    holding_power: 0.1