axis_0:
  ros__parameters:
    bus_number: 1
    board_address: 10

axis_1:
  ros__parameters:
    bus_number: 1
    board_address: 11

axis_2:
  ros__parameters:
    bus_number: 1
    board_address: 12

axis_3:
  ros__parameters:
    bus_number: 1
    board_address: 13